In [1]:
import pandas as pd

In [8]:
# Import the necessary libraries
import pandas as pd

# Import the dataset from this url https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
# Assign the url to a variable called url and create a dataframe named chipo.
url = 'comments.csv'
Dataset = pd.read_csv(url)

In [10]:
Dataset.head(10)

   id                    comment_text  user_id  photo_id           created_at
0   1                 unde at dolorem        2         1  2023-05-13 15:14:58
1   2                 quae ea ducimus        3         1  2023-05-13 15:14:58
2   3              alias a voluptatum        5         1  2023-05-13 15:14:58
3   4            facere suscipit sunt       14         1  2023-05-13 15:14:58
4   5          totam eligendi quaerat       17         1  2023-05-13 15:14:58
5   6              vitae quia aliquam       21         1  2023-05-13 15:14:58
6   7  exercitationem occaecati neque       24         1  2023-05-13 15:14:58
7   8                  sint ad fugiat       31         1  2023-05-13 15:14:58
8   9           nesciunt aut nesciunt       36         1  2023-05-13 15:14:58
9  10           laudantium ut nostrum       41         1  2023-05-13 15:14:58

In [11]:
Dataset.shape[0]

1000

In [12]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1000 non-null   int64
 1   comment_text  1000 non-null   object
 2   user_id       1000 non-null   int64
 3   photo_id      1000 non-null   int64
 4   created_at    1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [13]:
Dataset.shape

(1000, 5)

In [14]:
Dataset.shape[1]

5

In [15]:
Dataset.columns

Index(['id', 'comment_text', 'user_id', 'photo_id', 'created_at'], dtype='object')

In [16]:
Dataset.index

RangeIndex(start=0, stop=1000, step=1)

In [17]:
Dataset.values

array([[1, 'unde at dolorem', 2, 1, '2023-05-13 15:14:58'],
       [2, 'quae ea ducimus', 3, 1, '2023-05-13 15:14:58'],
       [3, 'alias a voluptatum', 5, 1, '2023-05-13 15:14:58'],
       ...,
       [998, 'dolorem dolor sed', 30, 35, '2023-05-13 15:14:58'],
       [999, 'dicta aut non', 32, 35, '2023-05-13 15:14:58'],
       [1000, 'mollitia et praesentium', 36, 35, '2023-05-13 15:14:58']],
      shape=(1000, 5), dtype=object)

In [21]:
column_data_type = Dataset['photo_id'].dtype
print(column_data_type)

int64

In [22]:
Dataset.sort_values("photo_id")

       id             comment_text  user_id  photo_id           created_at
0       1          unde at dolorem        2         1  2023-05-13 15:14:58
1       2          quae ea ducimus        3         1  2023-05-13 15:14:58
2       3       alias a voluptatum        5         1  2023-05-13 15:14:58
3       4     facere suscipit sunt       14         1  2023-05-13 15:14:58
4       5   totam eligendi quaerat       17         1  2023-05-13 15:14:58
..    ...                      ...      ...       ...                  ...
995   996     recusandae magnam ut       24        35  2023-05-13 15:14:58
996   997  incidunt qui blanditiis       27        35  2023-05-13 15:14:58
997   998        dolorem dolor sed       30        35  2023-05-13 15:14:58
998   999            dicta aut non       32        35  2023-05-13 15:14:58
999  1000  mollitia et praesentium       36        35  2023-05-13 15:14:58

[1000 rows x 5 columns]

In [23]:
Dataset.sort_values("photo_id", ascending=False)

       id             comment_text  user_id  photo_id           created_at
999  1000  mollitia et praesentium       36        35  2023-05-13 15:14:58
997   998        dolorem dolor sed       30        35  2023-05-13 15:14:58
998   999            dicta aut non       32        35  2023-05-13 15:14:58
996   997  incidunt qui blanditiis       27        35  2023-05-13 15:14:58
991   992       nisi eaque dolores       15        35  2023-05-13 15:14:58
..    ...                      ...      ...       ...                  ...
4       5   totam eligendi quaerat       17         1  2023-05-13 15:14:58
3       4     facere suscipit sunt       14         1  2023-05-13 15:14:58
2       3       alias a voluptatum        5         1  2023-05-13 15:14:58
1       2          quae ea ducimus        3         1  2023-05-13 15:14:58
0       1          unde at dolorem        2         1  2023-05-13 15:14:58

[1000 rows x 5 columns]

In [24]:
Dataset.sort_values(["photo_id", "user_id"])

       id             comment_text  user_id  photo_id           created_at
0       1          unde at dolorem        2         1  2023-05-13 15:14:58
1       2          quae ea ducimus        3         1  2023-05-13 15:14:58
2       3       alias a voluptatum        5         1  2023-05-13 15:14:58
3       4     facere suscipit sunt       14         1  2023-05-13 15:14:58
4       5   totam eligendi quaerat       17         1  2023-05-13 15:14:58
..    ...                      ...      ...       ...                  ...
995   996     recusandae magnam ut       24        35  2023-05-13 15:14:58
996   997  incidunt qui blanditiis       27        35  2023-05-13 15:14:58
997   998        dolorem dolor sed       30        35  2023-05-13 15:14:58
998   999            dicta aut non       32        35  2023-05-13 15:14:58
999  1000  mollitia et praesentium       36        35  2023-05-13 15:14:58

[1000 rows x 5 columns]

In [25]:
Dataset.sort_values(["photo_id", "comment_text"], ascending=[True, False])

      id                comment_text  user_id  photo_id           created_at
23    24           voluptatum sit id       91         1  2023-05-13 15:14:58
17    18    voluptas nemo blanditiis       71         1  2023-05-13 15:14:58
5      6          vitae quia aliquam       21         1  2023-05-13 15:14:58
0      1             unde at dolorem        2         1  2023-05-13 15:14:58
4      5      totam eligendi quaerat       17         1  2023-05-13 15:14:58
..   ...                         ...      ...       ...                  ...
992  993          est ullam suscipit       16        35  2023-05-13 15:14:58
997  998           dolorem dolor sed       30        35  2023-05-13 15:14:58
998  999               dicta aut non       32        35  2023-05-13 15:14:58
990  991  consequuntur aut veritatis       14        35  2023-05-13 15:14:58
993  994         aliquid sapiente ut       19        35  2023-05-13 15:14:58

[1000 rows x 5 columns]

In [26]:
subset_Dataset = Dataset["photo_id"]
print(subset_Dataset)

0       1
1       1
2       1
3       1
4       1
       ..
995    35
996    35
997    35
998    35
999    35
Name: photo_id, Length: 1000, dtype: int64

In [27]:
subset_Dataset1 = Dataset[["photo_id", "user_id", "comment_text"]]
print(subset_Dataset1)

     photo_id  user_id             comment_text
0           1        2          unde at dolorem
1           1        3          quae ea ducimus
2           1        5       alias a voluptatum
3           1       14     facere suscipit sunt
4           1       17   totam eligendi quaerat
..        ...      ...                      ...
995        35       24     recusandae magnam ut
996        35       27  incidunt qui blanditiis
997        35       30        dolorem dolor sed
998        35       32            dicta aut non
999        35       36  mollitia et praesentium

[1000 rows x 3 columns]

In [7]:
import pandas as pd

In [8]:
# Import the necessary libraries
import pandas as pd

# Import the dataset from this url https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
# Assign the url to a variable called url and create a dataframe named chipo.
url = 'comments.csv'
Dataset = pd.read_csv(url)

In [11]:
print(Dataset['comment_text'].dtype)

object

In [13]:
Dataset['photo_id'] = Dataset['user_id'] * Dataset['comment_text']

In [14]:
Dataset.head(20)

,id,comment_text,user_id,photo_id,created_at
0,1,unde at dolorem,2,unde at doloremunde at dolorem,2023-05-13 15:14:58
1,2,quae ea ducimus,3,quae ea ducimusquae ea ducimusquae ea ducimus,2023-05-13 15:14:58
2,3,alias a voluptatum,5,alias a voluptatumalias a voluptatumalias a vo...,2023-05-13 15:14:58
3,4,facere suscipit sunt,14,facere suscipit suntfacere suscipit suntfacere...,2023-05-13 15:14:58
4,5,totam eligendi quaerat,17,totam eligendi quaerattotam eligendi quaeratto...,2023-05-13 15:14:58
5,6,vitae quia aliquam,21,vitae quia aliquamvitae quia aliquamvitae quia...,2023-05-13 15:14:58
6,7,exercitationem occaecati neque,24,exercitationem occaecati nequeexercitationem o...,2023-05-13 15:14:58
7,8,sint ad fugiat,31,sint ad fugiatsint ad fugiatsint ad fugiatsint...,2023-05-13 15:14:58
8,9,nesciunt aut nesciunt,36,nesciunt aut nesciuntnesciunt aut nesciuntnesc...,2023-05-13 15:14:58
9,10,laudantium ut nostrum,41,laudantium ut nostrumlaudantium ut nostrumlaud...,2023-05-13 15:14:58
10,11,omnis aut asperiores,52,omnis aut asperioresomnis aut asperioresomnis ...,2023-05-13 15:14:58
11,12,et eum molestias,54,et eum molestiaset eum molestiaset eum molesti...,2023-05-13 15:14:58
12,13,alias pariatur neque,55,alias pariatur nequealias pariatur nequealias ...,2023-05-13 15:14:58
13,14,amet iure adipisci,57,amet iure adipisciamet iure adipisciamet iure ...,2023-05-13 15:14:58
14,15,cum enim repellat,62,cum enim repellatcum enim repellatcum enim rep...,2023-05-13 15:14:58
15,16,provident dolorem non,63,provident dolorem nonprovident dolorem nonprov...,2023-05-13 15:14:58
16,17,eos consequuntur impedit,66,eos consequuntur impediteos consequuntur imped...,2023-05-13 15:14:58
17,18,voluptas nemo blanditiis,71,voluptas nemo blanditiisvoluptas nemo blanditi...,2023-05-13 15:14:58
18,19,id fugit dolores,72,id fugit doloresid fugit doloresid fugit dolor...,2023-05-13 15:14:58
19,20,occaecati tenetur exercitationem,75,occaecati tenetur exercitationemoccaecati tene...,2023-05-13 15:14:58

In [15]:
def categorize_user(user_id):
    if user_id < 20:
        return 'Low'
    elif user_id < 50:
        return 'Medium'
    else:
        return 'High'